version: "2.10.2"
services:
  nacos:
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: nacos
    environment:
      # 支持主机名可以使用hostname,否则使用ip，默认ip
      - PREFER_HOST_MODE=ip
      # 单机模式
      - MODE=standalone
      # 数据源平台 支持mysql或不保存empty
      - SPRING_DATASOURCE_PLATFORM=mysql
      # mysql配置，!!!attention必须是mysql所在主机IP
      - MYSQL_SERVICE_HOST=192.168.1.16
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacos
    volumes:
      - ./logs:/Users/renxunzhen/tools/docker-compose/nacos/logs
      - ./conf:/Users/renxunzhen/tools/docker-compose/nacos/conf
    ports:
      - 8848:8848 
    restart: always
